/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboveMeRouteImport } from './routes/above-me'
import { Route as CameraRouteImport } from './routes/camera'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as IssRouteImport } from './routes/iss'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as PassesRouteImport } from './routes/passes'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as StarlinkRouteImport } from './routes/starlink'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as SatelliteIdRouteImport } from './routes/satellite.$id'
import { Route as SolarSystemIndexRouteImport } from './routes/solar-system.index'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'
import { Route as SolarSystemPlanetIndexRouteImport } from './routes/solar-system.$planet.index'
import { Route as SolarSystemPlanetMoonRouteImport } from './routes/solar-system.$planet.$moon'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboveMeRoute = AboveMeRouteImport.update({
  id: '/above-me',
  path: '/above-me',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraRoute = CameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const IssRoute = IssRouteImport.update({
  id: '/iss',
  path: '/iss',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const PassesRoute = PassesRouteImport.update({
  id: '/passes',
  path: '/passes',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StarlinkRoute = StarlinkRouteImport.update({
  id: '/starlink',
  path: '/starlink',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SatelliteIdRoute = SatelliteIdRouteImport.update({
  id: '/satellite/$id',
  path: '/satellite/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarSystemIndexRoute = SolarSystemIndexRouteImport.update({
  id: '/solar-system/',
  path: '/solar-system/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarSystemPlanetIndexRoute = SolarSystemPlanetIndexRouteImport.update({
  id: '/solar-system/$planet/',
  path: '/solar-system/$planet/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarSystemPlanetMoonRoute = SolarSystemPlanetMoonRouteImport.update({
  id: '/solar-system/$planet/$moon',
  path: '/solar-system/$planet/$moon',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/above-me': typeof AboveMeRoute
  '/camera': typeof CameraRoute
  '/community': typeof CommunityRoute
  '/iss': typeof IssRoute
  '/live': typeof LiveRoute
  '/missions': typeof MissionsRoute
  '/passes': typeof PassesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/starlink': typeof StarlinkRoute
  '/tracker': typeof TrackerRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/satellite/$id': typeof SatelliteIdRoute
  '/solar-system/': typeof SolarSystemIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/solar-system/$planet/$moon': typeof SolarSystemPlanetMoonRoute
  '/solar-system/$planet/': typeof SolarSystemPlanetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/above-me': typeof AboveMeRoute
  '/camera': typeof CameraRoute
  '/community': typeof CommunityRoute
  '/iss': typeof IssRoute
  '/live': typeof LiveRoute
  '/missions': typeof MissionsRoute
  '/passes': typeof PassesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/starlink': typeof StarlinkRoute
  '/tracker': typeof TrackerRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/satellite/$id': typeof SatelliteIdRoute
  '/solar-system': typeof SolarSystemIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/solar-system/$planet/$moon': typeof SolarSystemPlanetMoonRoute
  '/solar-system/$planet': typeof SolarSystemPlanetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/above-me': typeof AboveMeRoute
  '/camera': typeof CameraRoute
  '/community': typeof CommunityRoute
  '/iss': typeof IssRoute
  '/live': typeof LiveRoute
  '/missions': typeof MissionsRoute
  '/passes': typeof PassesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/starlink': typeof StarlinkRoute
  '/tracker': typeof TrackerRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/satellite/$id': typeof SatelliteIdRoute
  '/solar-system/': typeof SolarSystemIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/solar-system/$planet/$moon': typeof SolarSystemPlanetMoonRoute
  '/solar-system/$planet/': typeof SolarSystemPlanetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/above-me'
    | '/camera'
    | '/community'
    | '/iss'
    | '/live'
    | '/missions'
    | '/passes'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/starlink'
    | '/tracker'
    | '/auth/callback'
    | '/satellite/$id'
    | '/solar-system/'
    | '/api/stripe/webhook'
    | '/solar-system/$planet/$moon'
    | '/solar-system/$planet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/above-me'
    | '/camera'
    | '/community'
    | '/iss'
    | '/live'
    | '/missions'
    | '/passes'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/starlink'
    | '/tracker'
    | '/auth/callback'
    | '/satellite/$id'
    | '/solar-system'
    | '/api/stripe/webhook'
    | '/solar-system/$planet/$moon'
    | '/solar-system/$planet'
  id:
    | '__root__'
    | '/'
    | '/above-me'
    | '/camera'
    | '/community'
    | '/iss'
    | '/live'
    | '/missions'
    | '/passes'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/starlink'
    | '/tracker'
    | '/auth/callback'
    | '/satellite/$id'
    | '/solar-system/'
    | '/api/stripe/webhook'
    | '/solar-system/$planet/$moon'
    | '/solar-system/$planet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboveMeRoute: typeof AboveMeRoute
  CameraRoute: typeof CameraRoute
  CommunityRoute: typeof CommunityRoute
  IssRoute: typeof IssRoute
  LiveRoute: typeof LiveRoute
  MissionsRoute: typeof MissionsRoute
  PassesRoute: typeof PassesRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  StarlinkRoute: typeof StarlinkRoute
  TrackerRoute: typeof TrackerRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  SatelliteIdRoute: typeof SatelliteIdRoute
  SolarSystemIndexRoute: typeof SolarSystemIndexRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  SolarSystemPlanetMoonRoute: typeof SolarSystemPlanetMoonRoute
  SolarSystemPlanetIndexRoute: typeof SolarSystemPlanetIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/above-me': {
      id: '/above-me'
      path: '/above-me'
      fullPath: '/above-me'
      preLoaderRoute: typeof AboveMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iss': {
      id: '/iss'
      path: '/iss'
      fullPath: '/iss'
      preLoaderRoute: typeof IssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passes': {
      id: '/passes'
      path: '/passes'
      fullPath: '/passes'
      preLoaderRoute: typeof PassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starlink': {
      id: '/starlink'
      path: '/starlink'
      fullPath: '/starlink'
      preLoaderRoute: typeof StarlinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satellite/$id': {
      id: '/satellite/$id'
      path: '/satellite/$id'
      fullPath: '/satellite/$id'
      preLoaderRoute: typeof SatelliteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar-system/': {
      id: '/solar-system/'
      path: '/solar-system'
      fullPath: '/solar-system/'
      preLoaderRoute: typeof SolarSystemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar-system/$planet/': {
      id: '/solar-system/$planet/'
      path: '/solar-system/$planet'
      fullPath: '/solar-system/$planet/'
      preLoaderRoute: typeof SolarSystemPlanetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar-system/$planet/$moon': {
      id: '/solar-system/$planet/$moon'
      path: '/solar-system/$planet/$moon'
      fullPath: '/solar-system/$planet/$moon'
      preLoaderRoute: typeof SolarSystemPlanetMoonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboveMeRoute: AboveMeRoute,
  CameraRoute: CameraRoute,
  CommunityRoute: CommunityRoute,
  IssRoute: IssRoute,
  LiveRoute: LiveRoute,
  MissionsRoute: MissionsRoute,
  PassesRoute: PassesRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  StarlinkRoute: StarlinkRoute,
  TrackerRoute: TrackerRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  SatelliteIdRoute: SatelliteIdRoute,
  SolarSystemIndexRoute: SolarSystemIndexRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  SolarSystemPlanetMoonRoute: SolarSystemPlanetMoonRoute,
  SolarSystemPlanetIndexRoute: SolarSystemPlanetIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
